// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/api/ping/[pin].ts";
import * as $1 from "./routes/api/telegram/[secret].ts";
import * as $2 from "./routes/index.tsx";
import * as $3 from "./routes/ping/[pin].tsx";
import * as $$0 from "./islands/Ping.tsx";

const manifest = {
  routes: {
    "./routes/api/ping/[pin].ts": $0,
    "./routes/api/telegram/[secret].ts": $1,
    "./routes/index.tsx": $2,
    "./routes/ping/[pin].tsx": $3,
  },
  islands: {
    "./islands/Ping.tsx": $$0,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
